- name: Install PostgreSQL GPG apt Key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository 
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present

- name: Update repository cache
  apt:
    update_cache: yes

- name: Install PostgreSQL and dependency
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql-9.6
    - postgresql-contrib-9.6
    - libpq-dev
    - python-psycopg2
    - python3-pip

- name: Install psycopg2 for use Postgres module
  pip:
    name: psycopg2

- name: Create PostgreSQL User
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ psql_db_user }}"
    password: "{{ psql_db_user_pass }}"
    encrypted: True

- name: Create PostgreSQL DB
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{psql_db_name}}"
    owner: "{{ psql_db_user }}"
    template: template0
    encoding: UTF8
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'

- name: Ensure we have access from the new user to PostgreSQL
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{ psql_db_name }}"
    role: "{{ psql_db_user }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE

- name: Change PostgreSQL network binding
  lineinfile:
    path: /etc/postgresql/9.6/main/postgresql.conf
    regexp: '# listen_addresses'
    line: "listen_addresses = '*'"

- name: Change PostgreSQL pg_hba access
  lineinfile:
    path: /etc/postgresql/9.6/main/pg_hba.conf
    regexp: 'host  all  all 0.0.0.0/0 md5'
    line: 'host  all  all 0.0.0.0/0 md5'

- name: Start PostgreSQL server
  service:
    enabled: yes
    name: postgresql
    state: restarted
